version: "3"
services:
  nextjs-app:
    container_name: smartcine-nextjs-app
    restart: on-failure:3
    networks:
      - smartcine-network
    build:
      context: . # use the current directory as the build contexts
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - BABEL_ENV=${BABEL_ENV}
      - PORT=${PORT}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_API_VERSION=${NEXT_PUBLIC_API_VERSION}
      - NEXT_PUBLIC_API_TEST_TOKEN=${NEXT_PUBLIC_API_TEST_TOKEN}
networks:
  smartcine-network:
    external: true
